use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct SerializableColorScheme {
    pub primary: i64,
    pub onPrimary: i64,
    pub primaryContainer: i64,
    pub onPrimaryContainer: i64,
    pub inversePrimary: i64,
    pub secondary: i64,
    pub onSecondary: i64,
    pub secondaryContainer: i64,
    pub onSecondaryContainer: i64,
    pub tertiary: i64,
    pub onTertiary: i64,
    pub tertiaryContainer: i64,
    pub onTertiaryContainer: i64,
    pub background: i64,
    pub onBackground: i64,
    pub surface: i64,
    pub onSurface: i64,
    pub surfaceVariant: i64,
    pub onSurfaceVariant: i64,
    pub surfaceTint: i64,
    pub inverseSurface: i64,
    pub inverseOnSurface: i64,
    pub error: i64,
    pub onError: i64,
    pub errorContainer: i64,
    pub onErrorContainer: i64,
    pub outline: i64,
    pub outlineVariant: i64,
    pub scrim: i64,
}
